package appliances

// Defaults is the built-in catalog seeded into the persistent store on
// first run. Every URL is an official project source. Entries are marked
// Builtin so the UI can ask for a stricter double confirmation before
// they are deleted. Admins may edit URLs (to track new releases) and add
// new appliances at any time.
var Defaults = []Appliance{
	// ---- cloud ----
	{
		ID:          "ubuntu-26.04",
		Name:        "Ubuntu Server 26.04 LTS",
		Description: "Ubuntu Server 26.04 LTS (Resolute Raccoon) cloud image, ready for cloud-init.",
		Category:    "cloud",
		URL:         "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   863000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "Default login set via cloud-init (user + password). Daily build; URL tracks latest.",
	},
	{
		ID:          "ubuntu-24.04",
		Name:        "Ubuntu Server 24.04 LTS",
		Description: "Ubuntu Server 24.04 LTS (Noble) cloud image, ready for cloud-init.",
		Category:    "cloud",
		URL:         "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   624447488,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "Default login set via cloud-init (user + password). Auto-updated by Canonical.",
	},
	{
		ID:          "ubuntu-22.04",
		Name:        "Ubuntu Server 22.04 LTS",
		Description: "Ubuntu Server 22.04 LTS (Jammy) cloud image, ready for cloud-init.",
		Category:    "cloud",
		URL:         "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   624447488,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "Default login set via cloud-init (user + password). Auto-updated by Canonical.",
	},
	{
		ID:          "ubuntu-minimal-24.04",
		Name:        "Ubuntu Minimal 24.04 LTS",
		Description: "Ultra-small footprint Ubuntu 24.04 LTS Cloud image (~350MB).",
		Category:    "cloud",
		URL:         "https://cloud-images.ubuntu.com/minimal/daily/noble/current/noble-minimal-cloudimg-amd64.img",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   350000000,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      5,
		CloudInitSupported: true,
		Notes:       "Ultra-fast boot minimal cloud image with cloud-init.",
	},
	{
		ID:          "debian-13",
		Name:        "Debian 13 (trixie)",
		Description: "Debian 13 Trixie genericcloud image.",
		Category:    "cloud",
		URL:         "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   339214336,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. Auto-tracks latest Debian 13 testing builds.",
	},
	{
		ID:          "debian-12",
		Name:        "Debian 12 (bookworm)",
		Description: "Debian 12 Bookworm official genericcloud base image.",
		Category:    "cloud",
		URL:         "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   339214336,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. Stable release; auto-tracks latest point releases.",
	},
	{
		ID:          "debian-11",
		Name:        "Debian 11 (bullseye)",
		Description: "Debian 11 Bullseye genericcloud image.",
		Category:    "cloud",
		URL:         "https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   339214336,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "almalinux-9",
		Name:        "AlmaLinux 9",
		Description: "AlmaLinux 9 GenericCloud base image (100% RHEL binary compatible).",
		Category:    "cloud",
		URL:         "https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   650000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. Auto-tracks latest AlmaLinux 9 releases.",
	},
	{
		ID:          "almalinux-8",
		Name:        "AlmaLinux 8",
		Description: "AlmaLinux 8 GenericCloud image.",
		Category:    "cloud",
		URL:         "https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-latest.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   650000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "rocky-9",
		Name:        "Rocky Linux 9",
		Description: "Rocky Linux 9 GenericCloud base image.",
		Category:    "cloud",
		URL:         "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   645988352,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. Auto-tracks latest Rocky Linux 9 releases.",
	},
	{
		ID:          "rocky-8",
		Name:        "Rocky Linux 8",
		Description: "Rocky Linux 8 GenericCloud base image.",
		Category:    "cloud",
		URL:         "https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base.latest.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   645988352,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "centos-stream-9",
		Name:        "CentOS Stream 9",
		Description: "CentOS Stream 9 GenericCloud image.",
		Category:    "cloud",
		URL:         "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   1500000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. Auto-tracks latest CentOS 9 Stream.",
	},
	{
		ID:          "fedora-44",
		Name:        "Fedora 44 (Cloud)",
		Description: "Fedora 44 Cloud base image.",
		Category:    "cloud",
		URL:         "https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   583729152,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "arch-linux",
		Name:        "Arch Linux (cloud)",
		Description: "Arch Linux rolling release cloud image.",
		Category:    "cloud",
		URL:         "https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   556609024,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      5,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. Rolling release; URL tracks latest build.",
	},
	{
		ID:          "alpine-3.24",
		Name:        "Alpine Linux 3.24",
		Description: "Minimal Alpine Linux cloud image with cloud-init.",
		Category:    "cloud",
		// Alpine's cloud images (unlike every other distro in this
		// catalog) ship separate BIOS-only and UEFI-only qcow2 builds
		// instead of one hybrid image. Every KVM VM WebKVM creates
		// defaults to UEFI (q35 chipset), so the "-bios-" build used
		// to be selected here never boots: TianoCore reports "No
		// bootable option or device was found" because the guest disk
		// has no EFI System Partition, only a legacy BIOS boot sector.
		// Confirmed live: deploying this appliance produced a VM that
		// hung at the UEFI shell on every boot. Use the "-uefi-" build.
		URL:         "https://dl-cdn.alpinelinux.org/alpine/v3.24/releases/cloud/generic_alpine-3.24.1-x86_64-uefi-cloudinit-r0.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   201981952,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      5,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. Ultra-lightweight.",
	},
	{
		ID:          "opensuse-leap",
		Name:        "openSUSE Leap 16.1",
		Description: "openSUSE Leap 16.1 Minimal VM (cloud) image.",
		Category:    "cloud",
		URL:         "https://download.opensuse.org/distribution/leap/16.1/appliances/Leap-16.1-Minimal-VM.x86_64-Cloud-Build2.16.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   341735936,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "flatcar",
		Name:        "Flatcar Container Linux",
		Description: "Flatcar Container Linux (Stable release) for container workloads.",
		Category:    "cloud",
		URL:         "https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_qemu_image.img.bz2",
		Format:      "raw",
		Compression: "bz2",
		SizeBytes:   450000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      15,
		CloudInitSupported: true,
		Notes:       "Container-focused immutable OS. Auto-tracks current stable release.",
	},
	{
		ID:          "freebsd-14",
		Name:        "FreeBSD 14 (Cloud-Init)",
		Description: "FreeBSD 14-RELEASE with official Cloud-Init support.",
		Category:    "cloud",
		URL:         "https://download.freebsd.org/releases/VM-IMAGES/14.5-RELEASE/amd64/Latest/FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz",
		Format:      "qcow2",
		Compression: "xz",
		SizeBytes:   400000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "FreeBSD with cloud-init pre-configured.",
	},

	// ---- nas & home ----
	{
		ID:          "haos",
		Name:        "Home Assistant OS (HAOS)",
		Description: "Home Assistant Operating System (QEMU/KVM image).",
		Category:    "home",
		URL:         "https://github.com/home-assistant/operating-system/releases/download/18.2/haos_ova-18.2.qcow2.xz",
		Format:      "qcow2",
		Compression: "xz",
		SizeBytes:   535936800,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      20,
		CloudInitSupported: false,
		Notes:       "Configure via the Home Assistant web UI (http://homeassistant.local:8123). URL is version-locked; edit it to track a newer release.",
	},
	{
		ID:          "truenas-scale",
		Name:        "TrueNAS SCALE",
		Description: "TrueNAS SCALE 25.04 NAS/storage server (ISO installer). ZFS, Docker, VMs.",
		Category:    "nas",
		URL:         "https://download.truenas.com/TrueNAS-Fangtooth/25.04.0/TrueNAS-SCALE-25.04.0.iso",
		Format:      "raw",
		Compression: "none",
		SizeBytes:   2100000000,
		VCPUs:       4,
		RAMMB:       8192,
		DiskGB:      20,
		CloudInitSupported: false,
		Notes:       "ISO installer. Web UI at https://<ip> after install. Default root password set during install. Needs 8GB+ RAM.",
	},
	{
		ID:          "openmediavault",
		Name:        "OpenMediaVault",
		Description: "OpenMediaVault 8 NAS (ISO installer). Debian-based, plugins, SMB/NFS/iSCSI.",
		Category:    "nas",
		URL:         "https://sourceforge.net/projects/openmediavault/files/iso/8.3.1/openmediavault_8.3.1-amd64.iso/download",
		Format:      "raw",
		Compression: "none",
		SizeBytes:   1244774400,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      20,
		CloudInitSupported: false,
		Notes:       "ISO installer (OMV 8). Web UI at http://<ip> after install. Default: admin/openmediavault.",
	},

	// ---- router ----
	{
		ID:          "openwrt-23.05",
		Name:        "OpenWrt 23.05",
		Description: "OpenWrt x86_64 (EFI, ext4). Turnkey router/firewall image.",
		Category:    "router",
		URL:         "https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-23.05.5-x86-64-generic-ext4-combined-efi.img.gz",
		Format:      "raw",
		Compression: "gz",
		SizeBytes:   0,
		VCPUs:       1,
		RAMMB:       512,
		DiskGB:      2,
		CloudInitSupported: false,
		Notes:       "No default root password is set; SSH is disabled by default. Configure via LuCI (http://192.168.1.1).",
	},
	{
		ID:          "opnsense",
		Name:        "OPNsense",
		Description: "OPNsense x86_64 (VGA). Turnkey firewall/router image.",
		Category:    "router",
		URL:         "https://pkg.opnsense.org/releases/26.7/OPNsense-26.7-vga-amd64.img.bz2",
		Format:      "raw",
		Compression: "bz2",
		SizeBytes:   493886640,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      5,
		CloudInitSupported: false,
		Notes:       "Default login admin/opnsense. URL is version-locked; edit it to track a newer release.",
	},

	// ---- firewall (raw images, no cloud-init — configure via web UI on first boot) ----
	{
		ID:          "pfsense-ce",
		Name:        "pfSense CE",
		Description: "pfSense CE 2.8.1 firewall/router (serial console). Requires manual download via the Netgate Installer.",
		Category:    "router",
		URL:         "https://nyifiles.pfsense.org/mirror/downloads/pfSense-CE-memstick-serial-2.8.1-RELEASE-amd64.img.gz",
		Format:      "raw",
		Compression: "gz",
		SizeBytes:   200000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: false,
		Notes:       "Memstick-serial image boots directly. Default login admin/pfsense. Web GUI at https://<lan-ip>.",
	},
	{
		ID:          "ipfire",
		Name:        "IPFire",
		Description: "IPFire 2.29 firewall (raw flash image). Multi-zone (RED/GREEN/ORANGE/BLUE).",
		Category:    "router",
		URL:         "https://downloads.ipfire.org/releases/ipfire-2.x/2.29-core203/ipfire-2.29-core203-x86_64.img.xz",
		Format:      "raw",
		Compression: "xz",
		SizeBytes:   600000000,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      4,
		CloudInitSupported: false,
		Notes:       "Flash image. Setup wizard on first boot. Web GUI at https://<green-ip>:444.",
	},
	{
		ID:          "vyos",
		Name:        "VyOS",
		Description: "VyOS rolling release router CLI (live boot ISO). Configure via CLI: vyos/vyos.",
		Category:    "router",
		URL:         "https://github.com/vyos/vyos-nightly-build/releases/download/2026.09.01-0034-rolling/vyos-2026.09.01-0034-rolling-generic-amd64.iso",
		Format:      "raw",
		Compression: "none",
		SizeBytes:   673185792,
		VCPUs:       2,
		RAMMB:       4096,
		DiskGB:      10,
		CloudInitSupported: false,
		Notes:       "Rolling ISO boots as live system. Login vyos/vyos. Run 'install image' to persist, or configure live.",
	},

	// ---- 1-Click Helper Apps & Appliances (LXC Container & KVM VM Ready) ----
	{
		ID:                 "pihole",
		Name:               "Pi-hole",
		Description:        "Network-wide ad blocker via DNS sinkhole with web admin interface.",
		Category:           "networking",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               80,
		WebPath:            "/admin",
		Logo:               "pihole",
		DocumentationURL:   "https://pi-hole.net",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              512,
		DiskGB:             4,
		CloudInitSupported: true,
		Notes:              "Web UI on port 80 (/admin). DNS on port 53. Password displayed after provisioning.",
	},
	{
		ID:                 "adguard-home",
		Name:               "AdGuard Home",
		Description:        "Network-wide software for blocking ads and tracking with DNS privacy encryption.",
		Category:           "networking",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               3000,
		WebPath:            "/",
		Logo:               "adguard",
		DocumentationURL:   "https://adguard.com/adguard-home.html",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              512,
		DiskGB:             4,
		CloudInitSupported: true,
		Notes:              "Initial setup on port 3000. Web admin on port 80. DNS on port 53.",
	},
	{
		ID:                 "uptime-kuma",
		Name:               "Uptime Kuma",
		Description:        "Self-hosted monitoring tool with fancy UI, status pages, and multi-channel alerts.",
		Category:           "monitoring",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               3001,
		WebPath:            "/",
		Logo:               "uptimekuma",
		DocumentationURL:   "https://uptime.kuma.pet",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              512,
		DiskGB:             6,
		CloudInitSupported: true,
		Notes:              "Status dashboard on port 3001. Create admin account on first visit.",
	},
	{
		ID:                 "beszel",
		Name:               "Beszel Monitoring",
		Description:        "Lightweight server resource monitoring dashboard with docker container stats.",
		Category:           "monitoring",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               8090,
		WebPath:            "/",
		Logo:               "beszel",
		DocumentationURL:   "https://beszel.dev",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              512,
		DiskGB:             6,
		CloudInitSupported: true,
		Notes:              "Hub UI on port 8090. Agent metrics listening on port 8400.",
	},
	{
		ID:                 "vaultwarden",
		Name:               "Vaultwarden",
		Description:        "Lightweight Bitwarden compatible server written in Rust. Secure password manager.",
		Category:           "security",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               8080,
		WebPath:            "/",
		Logo:               "vaultwarden",
		DocumentationURL:   "https://github.com/dani-garcia/vaultwarden",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              512,
		DiskGB:             8,
		CloudInitSupported: true,
		Notes:              "Web vault on port 8080. HTTPS required for browser crypto extension sync.",
	},
	{
		ID:                 "docker-ce",
		Name:               "Docker CE & Compose",
		Description:        "Official Docker Engine with Compose plugin and systemd container runtime.",
		Category:           "devops",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               22,
		WebPath:            "/",
		Logo:               "docker",
		DocumentationURL:   "https://docs.docker.com/engine/",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             15,
		CloudInitSupported: true,
		Notes:              "Docker CE + Compose v2. Nested container support enabled by default.",
	},
	{
		ID:                 "portainer-ce",
		Name:               "Portainer CE",
		Description:        "Powerful container management UI for Docker environments and stacks.",
		Category:           "devops",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               9443,
		WebPath:            "/",
		Logo:               "portainer",
		DocumentationURL:   "https://docs.portainer.io",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             15,
		CloudInitSupported: true,
		Notes:              "Web UI on port 9443 (HTTPS). Create admin password on first visit.",
	},
	{
		ID:                 "n8n",
		Name:               "n8n Workflow Automation",
		Description:        "Fair-code workflow automation tool with 400+ integrations and AI capabilities.",
		Category:           "automation",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               5678,
		WebPath:            "/",
		Logo:               "n8n",
		DocumentationURL:   "https://docs.n8n.io",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             10,
		CloudInitSupported: true,
		Notes:              "Workflow Studio on port 5678. Setup admin account on first visit.",
	},
	{
		ID:                 "stirling-pdf",
		Name:               "Stirling-PDF",
		Description:        "Locally hosted one-stop-shop web application for all your PDF editing operations.",
		Category:           "productivity",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               8080,
		WebPath:            "/",
		Logo:               "stirlingpdf",
		DocumentationURL:   "https://github.com/Stirling-Tools/Stirling-PDF",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              1024,
		DiskGB:             8,
		CloudInitSupported: true,
		Notes:              "PDF Toolkit web UI available directly on port 8080.",
	},
	{
		ID:                 "nginx-proxy-manager",
		Name:               "Nginx Proxy Manager",
		Description:        "Easy reverse proxy management with free automatic Let's Encrypt SSL certificates.",
		Category:           "networking",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               81,
		WebPath:            "/",
		Logo:               "nginxproxymanager",
		DocumentationURL:   "https://nginxproxymanager.com",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              1024,
		DiskGB:             8,
		CloudInitSupported: true,
		Notes:              "Admin UI on port 81. HTTP on 80, HTTPS on 443. Default login: admin@example.com / changeme.",
	},
	{
		ID:                 "wireguard-easy",
		Name:               "WireGuard Easy",
		Description:        "Fast, modern WireGuard VPN server with beautiful web UI and QR-code client setup.",
		Category:           "security",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               51821,
		WebPath:            "/",
		Logo:               "wireguard",
		DocumentationURL:   "https://github.com/wg-easy/wg-easy",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              512,
		DiskGB:             6,
		CloudInitSupported: true,
		Notes:              "Web UI on port 51821. VPN port UDP 51820. Password shown after provisioning.",
	},
	{
		ID:                 "home-assistant",
		Name:               "Home Assistant Core",
		Description:        "Open source home automation that puts local control and privacy first.",
		Category:           "home",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               8123,
		WebPath:            "/",
		Logo:               "homeassistant",
		DocumentationURL:   "https://www.home-assistant.io",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             16,
		CloudInitSupported: true,
		Notes:              "Web dashboard on port 8123. Complete onboarding wizard on first visit.",
	},
	{
		ID:                 "jellyfin",
		Name:               "Jellyfin Media Server",
		Description:        "The Free Software Media System. Collect, manage, and stream your media files.",
		Category:           "media",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               8096,
		WebPath:            "/",
		Logo:               "jellyfin",
		DocumentationURL:   "https://jellyfin.org",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             20,
		CloudInitSupported: true,
		Notes:              "Media streaming on port 8096. Complete setup wizard in the browser.",
	},
	{
		ID:                 "grafana",
		Name:               "Grafana OSS",
		Description:        "Operational dashboards and visualization platform for Prometheus, logs and metrics.",
		Category:           "monitoring",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               3000,
		WebPath:            "/",
		Logo:               "grafana",
		DocumentationURL:   "https://grafana.com/docs/",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              1024,
		DiskGB:             10,
		CloudInitSupported: true,
		Notes:              "Dashboards on port 3000. Default login: admin / admin.",
	},
	{
		ID:                 "gitea",
		Name:               "Gitea",
		Description:        "Painless self-hosted Git service written in Go. Lightweight GitHub alternative.",
		Category:           "devops",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               3001,
		WebPath:            "/",
		Logo:               "gitea",
		DocumentationURL:   "https://docs.gitea.com",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              1,
		RAMMB:              1024,
		DiskGB:             10,
		CloudInitSupported: true,
		Notes:              "Web UI on port 3001. SSH git push/pull on port 22.",
	},
	{
		ID:                 "nextcloud",
		Name:               "Nextcloud Hub",
		Description:        "Self-hosted productivity platform. Files, contacts, calendar and office suite.",
		Category:           "productivity",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               80,
		WebPath:            "/nextcloud",
		Logo:               "nextcloud",
		DocumentationURL:   "https://docs.nextcloud.com",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             30,
		CloudInitSupported: true,
		Notes:              "Access Nextcloud at http://<ip>/nextcloud. Database credentials generated at deploy.",
	},
	{
		ID:                 "wordpress",
		Name:               "WordPress",
		Description:        "The world's most popular web publishing platform and CMS on LAMP stack.",
		Category:           "productivity",
		DefaultType:        "container",
		BaseImage:          "images:ubuntu/26.04",
		Port:               80,
		WebPath:            "/",
		Logo:               "wordpress",
		DocumentationURL:   "https://wordpress.org/documentation/",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             20,
		CloudInitSupported: true,
		Notes:              "Access site at http://<ip>/. Finish installer with generated DB credentials.",
	},
	{
		ID:                 "odoo",
		Name:               "Odoo Community ERP",
		Description:        "Open source ERP & CRM business management suite with integrated PostgreSQL.",
		Category:           "productivity",
		DefaultType:        "vm",
		BaseImage:          "images:ubuntu/26.04",
		Port:               8069,
		WebPath:            ":8069",
		Logo:               "odoo",
		DocumentationURL:   "https://www.odoo.com/documentation/",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              3072,
		DiskGB:             30,
		CloudInitSupported: true,
		Notes:              "Access Odoo at http://<ip>:8069. Complete initial database setup.",
	},
	{
		ID:                 "moodle",
		Name:               "Moodle LMS",
		Description:        "Open-source learning platform and course management system for educators.",
		Category:           "productivity",
		DefaultType:        "vm",
		BaseImage:          "images:ubuntu/26.04",
		Port:               80,
		WebPath:            "/moodle",
		Logo:               "moodle",
		DocumentationURL:   "https://docs.moodle.org",
		IsHelperScript:     true,
		URL:                "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img",
		BaseImageID:        "ubuntu-26.04",
		Format:             "qcow2",
		Compression:        "none",
		SizeBytes:          863000000,
		VCPUs:              2,
		RAMMB:              2048,
		DiskGB:             20,
		CloudInitSupported: true,
		Notes:              "Access Moodle at http://<ip>/moodle. Complete configuration in the web wizard.",
	},
}
