package appliances

// Defaults is the built-in catalog seeded into the persistent store on
// first run. Every URL is an official project source. Entries are marked
// Builtin so the UI can ask for a stricter double confirmation before
// they are deleted. Admins may edit URLs (to track new releases) and add
// new appliances at any time.
var Defaults = []Appliance{
	// ---- cloud ----
	{
		ID:          "ubuntu-24.04",
		Name:        "Ubuntu Server 24.04 LTS",
		Description: "Ubuntu Server 24.04 LTS (Noble) cloud image, ready for cloud-init.",
		Category:    "cloud",
		URL:         "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   624447488,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "Default login set via cloud-init (user + password).",
	},
	{
		ID:          "debian-13",
		Name:        "Debian 13 (trixie)",
		Description: "Debian 13 Trixie genericcloud image.",
		Category:    "cloud",
		URL:         "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   325000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "rocky-9",
		Name:        "Rocky Linux 9",
		Description: "Rocky Linux 9 GenericCloud base image.",
		Category:    "cloud",
		URL:         "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   645988352,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "centos-stream-9",
		Name:        "CentOS Stream 9",
		Description: "CentOS Stream 9 GenericCloud image.",
		Category:    "cloud",
		URL:         "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   1500000000,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "fedora-44",
		Name:        "Fedora 44 (Cloud)",
		Description: "Fedora 44 Cloud base image.",
		Category:    "cloud",
		URL:         "https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   583729152,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. URL is version-locked; edit it to track a newer release.",
	},
	{
		ID:          "arch-linux",
		Name:        "Arch Linux (cloud)",
		Description: "Arch Linux rolling release cloud image.",
		Category:    "cloud",
		URL:         "https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   556609024,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      5,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "alpine-3.24",
		Name:        "Alpine Linux 3.24",
		Description: "Minimal Alpine Linux cloud image with cloud-init.",
		Category:    "cloud",
		URL:         "https://dl-cdn.alpinelinux.org/alpine/v3.24/releases/cloud/generic_alpine-3.24.1-x86_64-bios-cloudinit-r0.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   183697408,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      5,
		CloudInitSupported: true,
		Notes:       "User via cloud-init.",
	},
	{
		ID:          "opensuse-leap",
		Name:        "openSUSE Leap 16.1",
		Description: "openSUSE Leap 16.1 Minimal VM (cloud) image.",
		Category:    "cloud",
		URL:         "https://download.opensuse.org/distribution/leap/16.1/appliances/Leap-16.1-Minimal-VM.x86_64-Cloud-Build2.1.qcow2",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   340395520,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      10,
		CloudInitSupported: true,
		Notes:       "User via cloud-init. URL is version-locked; edit it to track a newer release.",
	},

	// ---- nas ----
	{
		ID:          "home-assistant",
		Name:        "Home Assistant OS",
		Description: "Home Assistant Operating System (QEMU/KVM image).",
		Category:    "nas",
		URL:         "https://github.com/home-assistant/operating-system/releases/download/18.2/haos_ova-18.2.qcow2.xz",
		Format:      "qcow2",
		Compression: "xz",
		SizeBytes:   535936800,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      20,
		CloudInitSupported: false,
		Notes:       "Configure via the Home Assistant web UI (http://homeassistant.local:8123). URL is version-locked; edit it to track a newer release.",
	},

	// ---- router ----
	{
		ID:          "openwrt-23.05",
		Name:        "OpenWrt 23.05",
		Description: "OpenWrt x86_64 (EFI, ext4). Turnkey router/firewall image.",
		Category:    "router",
		URL:         "https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-23.05.5-x86-64-generic-ext4-combined-efi.img.gz",
		Format:      "raw",
		Compression: "gz",
		SizeBytes:   0,
		VCPUs:       1,
		RAMMB:       512,
		DiskGB:      2,
		CloudInitSupported: false,
		Notes:       "No default root password is set; SSH is disabled by default. Configure via LuCI (http://192.168.1.1).",
	},
	{
		ID:          "opnsense",
		Name:        "OPNsense",
		Description: "OPNsense x86_64 (VGA). Turnkey firewall/router image.",
		Category:    "router",
		URL:         "https://mirror.opnsense.org/releases/26.7/OPNsense-26.7-vga-amd64.img.bz2",
		Format:      "raw",
		Compression: "bz2",
		SizeBytes:   493886640,
		VCPUs:       1,
		RAMMB:       1024,
		DiskGB:      5,
		CloudInitSupported: false,
		Notes:       "Default login admin/opnsense. URL is version-locked; edit it to track a newer release.",
	},

	// ---- apps (installed on the Ubuntu cloud base via provisioning) ----
	{
		ID:          "wordpress",
		Name:        "WordPress",
		Description: "WordPress CMS on Ubuntu 24.04 (LAMP). Fully provisioned on first boot.",
		Category:    "app",
		URL:         "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
		BaseImageID: "ubuntu-24.04",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   624447488,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      20,
		CloudInitSupported: true,
		Notes:       "Access the site at http://<vm-ip>/ after provisioning. Admin credentials set on first visit.",
	},
	{
		ID:          "nextcloud",
		Name:        "Nextcloud",
		Description: "Nextcloud file sync/share server on Ubuntu 24.04 (LAMP). Provisioned on first boot.",
		Category:    "app",
		URL:         "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
		BaseImageID: "ubuntu-24.04",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   624447488,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      30,
		CloudInitSupported: true,
		Notes:       "Access Nextcloud at http://<vm-ip>/nextcloud after provisioning.",
	},
	{
		ID:          "odoo",
		Name:        "Odoo",
		Description: "Odoo Community ERP on Ubuntu 24.04. Provisioned on first boot.",
		Category:    "app",
		URL:         "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
		BaseImageID: "ubuntu-24.04",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   624447488,
		VCPUs:       2,
		RAMMB:       3072,
		DiskGB:      30,
		CloudInitSupported: true,
		Notes:       "Access Odoo at http://<vm-ip>:8069 after provisioning.",
	},
	{
		ID:          "moodle",
		Name:        "Moodle",
		Description: "Moodle LMS on Ubuntu 24.04 (LAMP). Provisioned on first boot.",
		Category:    "app",
		URL:         "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
		BaseImageID: "ubuntu-24.04",
		Format:      "qcow2",
		Compression: "none",
		SizeBytes:   624447488,
		VCPUs:       2,
		RAMMB:       2048,
		DiskGB:      20,
		CloudInitSupported: true,
		Notes:       "Access Moodle at http://<vm-ip>/moodle after provisioning.",
	},
}
