package configstore

// DefaultSchema returns the full schema of every configurable setting.
// Adding a new setting is a one-line change here — the UI picks it up
// automatically from /api/settings/schema.
//
// Phase 1.7-bis: trimmed to 12 wired fields. The other 18 from the
// Phase 1.7 release were never consumed by any backend code, so saving
// them via the UI was a no-op.
//
// Phase 1.7-bis-backup: the 3 backup settings (retention_count,
// retention_days, verify_on_write) were removed because backups are
// now write-only with manual cleanup. This is the set that actually
// does something today: 4 hot-reloadable (live) and 4 restart-required.
func DefaultSchema() Schema {
	oneTo100 := 1.0
	maxPort := float64(65535)
	zero := 0.0
	return Schema{Fields: []Field{
		// --- Server ---------------------------------------------------------
		{
			Key:         "server.bind_addr",
			Section:     "Server",
			Label:       "Bind address",
			Description: "Address the backend listens on. Use 127.0.0.1 in HTTPS-fronted installs so only the reverse proxy can reach the API. Restart required to apply.",
			Type:        FieldString,
			Default:     "127.0.0.1",
			Placeholder: "127.0.0.1",
		},
		{
			Key:         "server.port",
			Section:     "Server",
			Label:       "Port",
			Description: "TCP port the backend listens on. Restart required to apply.",
			Type:        FieldInt,
			Default:     8080,
			Min:         &oneTo100,
			Max:         &maxPort,
		},
		{
			Key:         "server.public_host",
			Section:     "Server",
			Label:       "Public host",
			Description: "IP or hostname baked into .rdp and .vv (SPICE) files. Must be reachable from the client machine. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "192.168.1.130",
		},
		{
			Key:         "server.trust_proxy",
			Section:     "Server",
			Label:       "Trust X-Forwarded-For",
			Description: "When on, the rate limiter and request logger use X-Forwarded-For as the client IP. Only enable behind a reverse proxy that strips client-supplied headers. Applies immediately.",
			Type:        FieldBool,
			Default:     false,
			HotReload:   true,
		},
		{
			Key:         "server.trusted_cidrs",
			Section:     "Server",
			Label:       "Trusted proxy CIDRs",
			Description: "Source IPs allowed to set X-Forwarded-For when Trust X-Forwarded-For is on, and allowed to bypass the login rate limiter (loopback is always included in both). Comma-free list, e.g. [\"10.0.0.0/8\"]. Leave empty unless your reverse proxy connects from a non-loopback address. Applies immediately.",
			Type:        FieldList,
			Default:     []string{},
			HotReload:   true,
		},
		{
			Key:         "server.rate_limit_enabled",
			Section:     "Server",
			Label:       "Global rate limit",
			Description: "Enable the per-IP token-bucket rate limit over the /api/* surface (V13-SEC-02). Requests authenticated with an API token (Bearer) and requests from trusted CIDRs are exempt. Applies immediately.",
			Type:        FieldBool,
			Default:     true,
			HotReload:   true,
		},
		{
			Key:         "server.rate_limit_rps",
			Section:     "Server",
			Label:       "Rate limit (requests/second per IP)",
			Description: "Token refill rate of the global per-IP rate limiter. Default 50. Applies to client buckets immediately.",
			Type:        FieldInt,
			Default:     50,
			Min:         &oneTo100,
			HotReload:   true,
		},
		{
			Key:         "server.rate_limit_burst",
			Section:     "Server",
			Label:       "Rate limit burst",
			Description: "Bucket capacity of the global per-IP rate limiter (peak requests an IP may send in a short burst). Default 100. Applies to client buckets immediately.",
			Type:        FieldInt,
			Default:     100,
			Min:         &oneTo100,
			HotReload:   true,
		},
		{
			Key:         "server.tls_cert",
			Section:     "Server",
			Label:       "TLS certificate",
			Description: "Path to the TLS certificate (PEM). Usually DATA_DIR/certs/webkvm.crt generated by the installer. When set together with server.tls_key the backend serves HTTPS directly. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "/opt/webkvm/certs/webkvm.crt",
		},
		{
			Key:         "server.tls_key",
			Section:     "Server",
			Label:       "TLS private key",
			Description: "Path to the TLS private key (PEM). Usually DATA_DIR/certs/webkvm.key. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "/opt/webkvm/certs/webkvm.key",
		},
		{
			Key:         "server.tls_domain",
			Section:     "Server",
			Label:       "TLS domain (Let's Encrypt)",
			Description: "Public hostname that resolves to this server. When set, the backend obtains a real Let's Encrypt certificate automatically (autocert) and falls back to the TLS certificate above if the domain can't be validated. Leave empty for self-signed only. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "webkvm.example.com",
		},
		{
			Key:         "server.incus_enabled",
			Section:     "Server",
			Label:       "Enable Incus containers",
			Description: "Optional container backend (LXC via Incus), alongside KVM VMs. Requires the Incus daemon to be reachable. Restart required to apply. The default is seeded from the WEBKVM_INCUS_ENABLED env var the first time this setting is created, so an existing install using that env var isn't silently disabled on upgrade — from then on this value is authoritative and the env var is ignored.",
			Type:        FieldBool,
			Default:     false, // placeholder; cmd/server/main.go patches this to cfg.IncusEnabled before configstore.New
		},

		// --- Auth -----------------------------------------------------------
		{
			Key:         "auth.token_ttl",
			Section:     "Auth",
			Label:       "Session token TTL",
			Description: "Lifetime of a logged-in session. Applies to new tokens; existing tokens keep their original expiry. Use short values for shared workstations.",
			Type:        FieldDuration,
			Default:     "24h",
			HotReload:   true,
		},
		{
			Key:         "auth.allow_api_tokens",
			Section:     "Auth",
			Label:       "Enable API tokens",
			Description: "When on, users can authenticate with long-lived API tokens (Bearer wvmb_…) in addition to session JWTs. Disable to force session cookies only. Applies immediately.",
			Type:        FieldBool,
			Default:     true,
			HotReload:   true,
		},

		// --- Logging --------------------------------------------------------
		{
			Key:         "logging.level",
			Section:     "Logging",
			Label:       "Log level",
			Description: "Minimum log level emitted to the journal/file: debug, info, warn, error. Applies immediately.",
			Type:        FieldEnum,
			Enum:        []string{"debug", "info", "warn", "error"},
			Default:     "info",
			HotReload:   true,
		},
		{
			Key:         "logging.format",
			Section:     "Logging",
			Label:       "Log format",
			Description: "json (structured) or text (human-readable). Restart required to apply.",
			Type:        FieldEnum,
			Enum:        []string{"json", "text"},
			Default:     "json",
		},

		// --- Network --------------------------------------------------------
		{
			Key:         "network.vlan_aware_default",
			Section:     "Network",
			Label:       "New bridges VLAN-aware by default",
			Description: "When on, Linux bridges created via the UI start with vlan_filtering=1 unless the create request says otherwise. Requires kernel >= 4.3. Applies to the next bridge you create, no restart needed.",
			Type:        FieldBool,
			Default:     false,
			HotReload:   true,
		},
		// --- Backup ---------------------------------------------------------
		// Re-added (Phase 1.7-bis-backup had removed the 3 old backup
		// settings as unused, but cmd/server/main.go never stopped reading
		// these 2 particular keys — they were consumed via a closure
		// re-evaluated on every real backup run, so no operator could ever
		// actually turn them on since the schema never exposed them).
		// Both are read live per backup run, not just at startup.
		{
			Key:         "backup.max_file_size_mb",
			Section:     "Backup",
			Label:       "Max backup file size (MB)",
			Description: "Skip any single VM disk larger than this during a backup run (0 = no limit). Applies to the next backup run, no restart needed.",
			Type:        FieldInt,
			Default:     0,
			Min:         &zero,
			HotReload:   true,
		},
		{
			Key:         "backup.verify_on_write",
			Section:     "Backup",
			Label:       "Verify backups after writing",
			Description: "Re-read and checksum every backup archive right after it's written, failing the job on a mismatch. Applies to the next backup run, no restart needed.",
			Type:        FieldBool,
			Default:     false,
			HotReload:   true,
		},
	}}
}
