package configstore

// DefaultSchema returns the full schema of every configurable setting.
// Adding a new setting is a one-line change here — the UI picks it up
// automatically from /api/settings/schema.
//
// Phase 1.7-bis: trimmed to 12 wired fields. The other 18 from the
// Phase 1.7 release were never consumed by any backend code, so saving
// them via the UI was a no-op.
//
// Phase 1.7-bis-backup: the 3 backup settings (retention_count,
// retention_days, verify_on_write) were removed because backups are
// now write-only with manual cleanup. This is the set that actually
// does something today: 4 hot-reloadable (live) and 4 restart-required.
func DefaultSchema() Schema {
	oneTo100 := 1.0
	maxPort := float64(65535)
	return Schema{Fields: []Field{
		// --- Server ---------------------------------------------------------
		{
			Key:         "server.bind_addr",
			Section:     "Server",
			Label:       "Bind address",
			Description: "Address the backend listens on. Use 127.0.0.1 in HTTPS-fronted installs so only the reverse proxy can reach the API. Restart required to apply.",
			Type:        FieldString,
			Default:     "127.0.0.1",
			Placeholder: "127.0.0.1",
		},
		{
			Key:         "server.port",
			Section:     "Server",
			Label:       "Port",
			Description: "TCP port the backend listens on. Restart required to apply.",
			Type:        FieldInt,
			Default:     8080,
			Min:         &oneTo100,
			Max:         &maxPort,
		},
		{
			Key:         "server.public_host",
			Section:     "Server",
			Label:       "Public host",
			Description: "IP or hostname baked into .rdp and .vv (SPICE) files. Must be reachable from the client machine. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "192.168.1.130",
		},
		{
			Key:         "server.trust_proxy",
			Section:     "Server",
			Label:       "Trust X-Forwarded-For",
			Description: "When on, the rate limiter and request logger use X-Forwarded-For as the client IP. Only enable behind a reverse proxy that strips client-supplied headers. Applies immediately.",
			Type:        FieldBool,
			Default:     false,
			HotReload:   true,
		},
		{
			Key:         "server.tls_cert",
			Section:     "Server",
			Label:       "TLS certificate",
			Description: "Path to the TLS certificate (PEM). Usually DATA_DIR/certs/webkvm.crt generated by the installer. When set together with server.tls_key the backend serves HTTPS directly. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "/opt/webkvm/certs/webkvm.crt",
		},
		{
			Key:         "server.tls_key",
			Section:     "Server",
			Label:       "TLS private key",
			Description: "Path to the TLS private key (PEM). Usually DATA_DIR/certs/webkvm.key. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "/opt/webkvm/certs/webkvm.key",
		},
		{
			Key:         "server.tls_domain",
			Section:     "Server",
			Label:       "TLS domain (Let's Encrypt)",
			Description: "Public hostname that resolves to this server. When set, the backend obtains a real Let's Encrypt certificate automatically (autocert) and falls back to the TLS certificate above if the domain can't be validated. Leave empty for self-signed only. Restart required to apply.",
			Type:        FieldString,
			Default:     "",
			Placeholder: "webkvm.example.com",
		},

		// --- Auth -----------------------------------------------------------
		{
			Key:         "auth.token_ttl",
			Section:     "Auth",
			Label:       "Session token TTL",
			Description: "Lifetime of a logged-in session. Applies to new tokens; existing tokens keep their original expiry. Use short values for shared workstations.",
			Type:        FieldDuration,
			Default:     "24h",
			HotReload:   true,
		},
		{
			Key:         "auth.allow_api_tokens",
			Section:     "Auth",
			Label:       "Enable API tokens",
			Description: "When on, users can authenticate with long-lived API tokens (Bearer wvmb_…) in addition to session JWTs. Disable to force session cookies only. Applies immediately.",
			Type:        FieldBool,
			Default:     true,
			HotReload:   true,
		},

		// --- Logging --------------------------------------------------------
		{
			Key:         "logging.level",
			Section:     "Logging",
			Label:       "Log level",
			Description: "Minimum log level emitted to the journal/file: debug, info, warn, error. Applies immediately.",
			Type:        FieldEnum,
			Enum:        []string{"debug", "info", "warn", "error"},
			Default:     "info",
			HotReload:   true,
		},
		{
			Key:         "logging.format",
			Section:     "Logging",
			Label:       "Log format",
			Description: "json (structured) or text (human-readable). Restart required to apply.",
			Type:        FieldEnum,
			Enum:        []string{"json", "text"},
			Default:     "json",
		},

		// --- Network --------------------------------------------------------
		{
			Key:         "network.vlan_aware_default",
			Section:     "Network",
			Label:       "New bridges VLAN-aware by default",
			Description: "When on, Linux bridges created via the UI start with vlan_filtering=1. Requires kernel >= 4.3. Restart required to apply.",
			Type:        FieldBool,
			Default:     false,
		},
	}}
}
