package main

import (
	"crypto/tls"
	"log/slog"
	"path/filepath"

	"golang.org/x/crypto/acme/autocert"

	"webkvm/internal/configstore"
)

// TLSMode describes how the backend terminates TLS.
type TLSMode string

const (
	tlsModeOff         TLSMode = "off"
	tlsModeSelfSigned  TLSMode = "selfsigned"
	tlsModeLetsEncrypt TLSMode = "letsencrypt"
)

// configureTLS builds the *tls.Config for the backend HTTP server based on
// the persisted server.tls_* settings:
//
//   - server.tls_domain set  -> Let's Encrypt via autocert (automatic
//     issuance + renewal, cache under DATA_DIR/tls). The certificate pair
//     from server.tls_cert / server.tls_key is used as a fallback when the
//     domain cannot be validated (LAN hostname, no public route), so a
//     misconfigured domain never takes the server down.
//   - server.tls_cert + server.tls_key set -> the backend serves HTTPS
//     directly with that pair (typically a self-signed cert generated by the
//     installer, SAN = localhost + hostname.local + LAN IP [+ domain]).
//   - neither -> plain HTTP (previous behaviour).
//
// It returns the TLS config (nil means HTTP-only) and the effective mode.
func configureTLS(store *configstore.Store, dataDir string, logger *slog.Logger) (*tls.Config, TLSMode) {
	tlsCert := store.GetString("server.tls_cert")
	tlsKey := store.GetString("server.tls_key")
	tlsDomain := store.GetString("server.tls_domain")

	if tlsDomain == "" && (tlsCert == "" || tlsKey == "") {
		return nil, tlsModeOff
	}

	conf := &tls.Config{MinVersion: tls.VersionTLS12}

	// Load the installer-provided (or operator-supplied) certificate pair.
	var fallback *tls.Certificate
	if tlsCert != "" && tlsKey != "" {
		if c, err := tls.LoadX509KeyPair(tlsCert, tlsKey); err != nil {
			logger.Warn("tls_cert_load_failed", "cert", tlsCert, "err", err)
		} else {
			fallback = &c
		}
	}

	if tlsDomain != "" {
		cacheDir := filepath.Join(dataDir, "tls")
		m := &autocert.Manager{
			Prompt:     autocert.AcceptTOS,
			Cache:      autocert.DirCache(cacheDir),
			HostPolicy: autocert.HostWhitelist(tlsDomain),
		}
		conf.GetCertificate = func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
			cert, err := m.GetCertificate(hello)
			if err == nil {
				return cert, nil
			}
			if fallback != nil {
				return fallback, nil
			}
			return nil, err
		}
		return conf, tlsModeLetsEncrypt
	}

	if fallback == nil {
		return nil, tlsModeOff
	}
	conf.Certificates = []tls.Certificate{*fallback}
	return conf, tlsModeSelfSigned
}