<script>
  /**
   * Icon — declarative wrapper around @lucide/svelte.
   *
   * Usage: <Icon name="computer" size={16} />
   *
   * This exists so the navigation items, header icons, and any
   * other place that needs a pictogram don't have to import a
   * specific lucide component (which would force us to keep
   * parallel lists of "name → component" in multiple files).
   *
   * Sizes are in pixels (not Tailwind classes) because they map
   * directly to lucide's `size` prop. Pass `class` for color /
   * stroke overrides (e.g. `class="text-muted-foreground"`).
   */
  import {
    Server,
    HardDrive,
    Network,
    Users,
    Settings as SettingsIcon,
    Activity,
    Archive,
    Computer,
    Terminal,
    Power,
    LogOut,
    Search,
    ChevronLeft,
    ChevronRight,
    Menu,
    X,
    Plus,
    Trash2,
    Pencil,
    Eye,
    EyeOff,
    Info,
    AlertTriangle,
    AlertCircle,
    CheckCircle2,
    Check,
    Loader2,
    RefreshCw,
    Download,
    Upload,
    Copy,
    Play,
    Square,
    RotateCw,
    RotateCcw,
    Pause,
    Camera,
    Save,
    HelpCircle,
    PanelLeft,
    Clock,
    Disc,
    Lock,
    Zap,
    ArrowRight,
    ArrowRightLeft,
    Shield,
    FileText,
    LayoutGrid,
    Key,
    Monitor,
    Maximize,
    Minimize,
    Maximize2,
    Minimize2,
    Keyboard,
    MousePointer,
    ExternalLink,
    CheckSquare,
    QrCode,
    ChevronDown,
    ChevronUp,
    Sun,
    Moon,
    Sparkles,
    Package,
    Box,
    Layers,
    Cpu,
    Globe,
    Code,
    Tag,
    Volume2,
    Image as ImageIcon,
    Gauge,
    Pin,
    GripVertical,
    Boxes,
    SearchX,
    FolderOpen,
    Usb,
    CircuitBoard,
    CalendarClock,
    ShieldOff,
    BellOff,
  } from '@lucide/svelte';

  const registry = {
    server: Server,
    hardDrive: HardDrive,
    // Kebab-case alias, matching the 'alert-triangle' pair below: both
    // spellings appear in the routes and a miss renders a grey dot.
    'hard-drive': HardDrive,
    network: Network,
    users: Users,
    settings: SettingsIcon,
    activity: Activity,
    archive: Archive,
    computer: Computer,
    monitor: Monitor,
    terminal: Terminal,
    power: Power,
    logOut: LogOut,
    search: Search,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    menu: Menu,
    x: X,
    plus: Plus,
    trash: Trash2,
    pencil: Pencil,
    eye: Eye,
    eyeOff: EyeOff,
    info: Info,
    warning: AlertTriangle,
    error: AlertCircle,
    success: CheckCircle2,
    check: Check,
    spinner: Loader2,
    refresh: RefreshCw,
    download: Download,
    upload: Upload,
    copy: Copy,
    play: Play,
    stop: Square,
    restart: RotateCw,
    resetDefault: RotateCcw,
    'rotate-ccw': RotateCcw,
    rotateCcw: RotateCcw,
    pause: Pause,
    camera: Camera,
    save: Save,
    help: HelpCircle,
    panelLeft: PanelLeft,
    clock: Clock,
    disc: Disc,
    lock: Lock,
    zap: Zap,
    tag: Tag,
    'volume-2': Volume2,
    volume2: Volume2,
    'alert-triangle': AlertTriangle,
    alertTriangle: AlertTriangle,
    arrowRight: ArrowRight,
    arrowRightLeft: ArrowRightLeft,
    shield: Shield,
    fileText: FileText,
    grid: LayoutGrid,
    key: Key,
    maximize: Maximize,
    minimize: Minimize,
    'maximize-2': Maximize2,
    'minimize-2': Minimize2,
    keyboard: Keyboard,
    'mouse-pointer': MousePointer,
    mousePointer: MousePointer,
    'external-link': ExternalLink,
    externalLink: ExternalLink,
    'check-square': CheckSquare,
    checkSquare: CheckSquare,
    qrCode: QrCode,
    'qr-code': QrCode,
    sun: Sun,
    moon: Moon,
    sparkles: Sparkles,
    package: Package,
    box: Box,
    layers: Layers,
    cpu: Cpu,
    globe: Globe,
    code: Code,
    image: ImageIcon,
    gauge: Gauge,
    pin: Pin,
    gripVertical: GripVertical,
    boxes: Boxes,
    searchX: SearchX,
    'search-x': SearchX,
    empty: SearchX,
    folderOpen: FolderOpen,
    'folder-open': FolderOpen,
    usb: Usb,
    circuitBoard: CircuitBoard,
    'circuit-board': CircuitBoard,
    calendarClock: CalendarClock,
    'calendar-clock': CalendarClock,
    shieldOff: ShieldOff,
    'shield-off': ShieldOff,
    bellOff: BellOff,
    'bell-off': BellOff,
  };

  let { name, size = 16, class: className = '' } = $props();

  const Component = $derived(registry[name]);
</script>

{#if Component}
  <Component {size} class={className} strokeWidth={1.75} />
{:else}
  <!-- Fallback: render a small dot so missing icons are obvious in QA. -->
  <span
    class="inline-block rounded-full bg-muted {className}"
    style="width: {size}px; height: {size}px"
    aria-hidden="true"
  ></span>
{/if}
