package helperscripts

import (
	_ "embed"
	"fmt"
	"regexp"
	"strings"
)

// shimScript is WebKVM's compatibility layer, embedded so a deployment
// never depends on a file being present next to the binary.
//
//go:embed shim.sh
var shimScript string

// Shim returns the compatibility layer source, for tests and for the API
// endpoint that lets an admin read exactly what will run.
func Shim() string { return shimScript }

// slugRE constrains a slug to what upstream file names actually contain.
// This is the only thing standing between a catalog entry and a URL that
// gets fetched and executed as root, so it is deliberately strict:
// no dots, no slashes, no percent escapes, nothing that could climb out
// of the install/ directory or point at another host.
var slugRE = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,63}$`)

// ValidSlug reports whether slug is safe to interpolate into an upstream
// URL.
func ValidSlug(slug string) bool { return slugRE.MatchString(slug) }

// BuildProvisionScript returns the script WebKVM runs inside a freshly
// created container to install app.
//
// The result is a three-part document: a header recording provenance,
// the WebKVM shim, and a small runner that downloads the *unmodified*
// upstream installer and sources it. The installer is fetched at run
// time rather than baked in because it is the part that changes often
// upstream, and pinning a stale copy would install outdated software
// while appearing to work.
//
// The script is not a sandbox. It runs third-party shell as root by
// design — that is what a helper script is. The safety story lives
// elsewhere: an explicit admin action, a validated slug, a fixed
// upstream host, and an audit entry.
func BuildProvisionScript(s Script) (string, error) {
	if !ValidSlug(s.Slug) {
		return "", fmt.Errorf("invalid script id %q", s.Slug)
	}

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by WebKVM. Installs a community-scripts application.\n")
	b.WriteString("#\n")
	b.WriteString("# Upstream installer: " + InstallURL(s.Slug) + "\n")
	b.WriteString("# Upstream launcher:  " + LauncherURL(s.Slug) + "\n")
	b.WriteString("# License: MIT (community-scripts ORG)\n")
	b.WriteString("#\n")
	b.WriteString("# The installer below is run unmodified. WebKVM only supplies the\n")
	b.WriteString("# container-lifecycle helpers it expects to find (see shim below).\n")
	b.WriteString("\n")

	// shellQuote, not plain interpolation: names come from upstream APP=
	// and contain spaces, apostrophes and ampersands.
	b.WriteString("export APP=" + shellQuote(s.Name) + "\n")
	b.WriteString("export APPLICATION=" + shellQuote(s.Name) + "\n")
	b.WriteString("export WEBKVM_APP_SLUG=" + shellQuote(s.Slug) + "\n\n")

	b.WriteString("# ---- WebKVM compatibility shim ----\n")
	b.WriteString(shimScript)
	b.WriteString("\n# ---- end shim ----\n\n")

	b.WriteString(`_installer=/usr/local/share/webkvm/app-install.sh
msg_info "Downloading installer for ${APP}"
if ! curl -fsSL --retry 3 --retry-delay 2 --max-time 120 -o "$_installer" ` +
		shellQuote(InstallURL(s.Slug)) + `; then
  msg_error "Cannot download the installer for ${APP}"
  exit 92
fi
# A truncated or error-page download would otherwise be sourced as if it
# were a real installer, failing in confusing ways much later.
if ! head -c 2048 "$_installer" | grep -q '#!/usr/bin/env bash'; then
  msg_error "Downloaded installer does not look like a shell script"
  exit 93
fi
msg_ok "Downloaded installer for ${APP}"

# Sourced rather than executed: the installer calls helpers defined
# above, which a child bash process would not inherit (functions are not
# exported).
source "$_installer"
`)

	if s.Port > 0 {
		b.WriteString("\nmsg_ok \"Reachable on port " + fmt.Sprint(s.Port) + s.WebPath + "\"\n")
	}
	return b.String(), nil
}

// shellQuote renders s as a single-quoted shell word.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
