package firewall

import (
	"errors"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// HostPorts returns the essential host ports that must always be
// reachable. The web UI port is passed in; SSH (22) and the default
// noVNC range are hard-coded as safety rails.
func HostPorts(webPort int) []int {
	return []int{22, webPort, 5900, 5901, 5902, 5903}
}

// IPResolver returns the current IPv4 of a VM (empty when off/no lease).
type IPResolver func(vmID string) string

// Manager builds and applies the nftables ruleset for every VM.
type Manager struct {
	store   *Store
	resolve IPResolver
	webPort int
	logger  *slog.Logger
}

// NewManager wires the store, the IP resolver (usually
// libvirt.Connector.GetDomainIP) and the web UI port.
func NewManager(store *Store, resolve IPResolver, webPort int, logger *slog.Logger) *Manager {
	if logger == nil {
		logger = slog.Default()
	}
	return &Manager{store: store, resolve: resolve, webPort: webPort, logger: logger}
}

// Apply rebuilds and applies the whole ruleset. It returns a map of
// VMID -> applied/pending forward counts for the UI.
func (m *Manager) Apply() (map[string]int, error) {
	ruleset := m.BuildRuleset()
	pending := map[string]int{}

	if ruleset == "" {
		// No rules at all: flush the webkvm table (delete if exists).
		if err := m.flushTable(); err != nil {
			return nil, err
		}
		return pending, nil
	}

	if err := m.applyRuleset(ruleset); err != nil {
		return nil, err
	}

	// Recompute applied/pending per VM.
	for _, fw := range m.store.All() {
		pend := 0
		for _, f := range fw.Forwards {
			if !f.Applied {
				pend++
			}
		}
		if pend > 0 {
			pending[fw.VMID] = pend
		}
	}
	return pending, nil
}

// BuildRuleset renders the nftables ruleset text for all VMs. Empty
// string means "no rules".
func (m *Manager) BuildRuleset() string {
	all := m.store.All()
	if len(all) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("# Generated by webkvm — do not edit manually\n")
	// The table is declared here (add semantics). The caller deletes
	// the existing webkvm table before applying, so "add" never
	// collides. No `flush` is needed and `flush` would fail the first
	// time the table doesn't exist yet.
	b.WriteString("table ip webkvm {\n")

	// Input chain: policy accept, safety rails first, then rules.
	b.WriteString("\tchain input {\n")
	b.WriteString("\t\ttype filter hook input priority filter; policy accept;\n")
	for _, p := range HostPorts(m.webPort) {
		fmt.Fprintf(&b, "\t\ttcp dport %d accept\n", p)
	}
	for _, fw := range all {
		for _, r := range fw.Rules {
			if !validProto(r.Proto) || r.Port < 1 || r.Port > 65535 {
				continue
			}
			if r.Action != "allow" && r.Action != "drop" {
				continue
			}
			for _, p := range protoList(r.Proto) {
				fmt.Fprintf(&b, "\t\t%s dport %d %s\n", p, r.Port, r.Action)
			}
		}
	}
	b.WriteString("\t}\n")

	// Prerouting chain: DNAT port forwards.
	hasForward := false
	for _, fw := range all {
		for i := range fw.Forwards {
			f := &fw.Forwards[i]
			if !validProto(f.Proto) || f.HostPort < 1 || f.HostPort > 65535 || f.GuestPort < 1 || f.GuestPort > 65535 {
				f.Applied = false
				continue
			}
			ip := f.TargetIP
			if ip == "" && m.resolve != nil {
				ip = m.resolve(fw.VMID)
			}
			if net.ParseIP(ip) == nil {
				// Can't resolve: mark pending, skip rule.
				f.Applied = false
				continue
			}
			f.Applied = true
			if !hasForward {
				b.WriteString("\tchain prerouting {\n")
				b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")
				hasForward = true
			}
			for _, p := range protoList(f.Proto) {
				fmt.Fprintf(&b, "\t\t%s dport %d dnat to %s:%d\n", p, f.HostPort, ip, f.GuestPort)
			}
		}
	}
	if hasForward {
		b.WriteString("\t}\n")

		// Postrouting: masquerade replies only toward forwarded VMs.
		var targets []string
		for _, fw := range all {
			for i := range fw.Forwards {
				f := &fw.Forwards[i]
				if f.Applied && net.ParseIP(f.TargetIP) != nil {
					targets = append(targets, f.TargetIP)
				}
			}
		}
		if len(targets) > 0 {
			b.WriteString("\tchain postrouting {\n")
			b.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")
			fmt.Fprintf(&b, "\t\tip daddr { %s } masquerade\n", strings.Join(targets, ", "))
			b.WriteString("\t}\n")
		}
	}

	b.WriteString("}\n")
	return b.String()
}

// applyRuleset removes any existing webkvm table (best-effort) then
// validates (-c) and applies (-f) the new ruleset atomically. Deleting
// only our own dedicated table is safe: libvirt's filter/nat tables and
// any other subsystem's rules are untouched.
func (m *Manager) applyRuleset(ruleset string) error {
	tmp := filepath.Join(os.TempDir(), "webkvm-nft.rules")
	if err := os.WriteFile(tmp, []byte(ruleset), 0o600); err != nil {
		return err
	}
	defer os.Remove(tmp)

	// Drop the old webkvm table first so the "add table" in the
	// ruleset succeeds. If it doesn't exist, that's fine (error).
	_ = exec.Command("nft", "delete", "table", "ip", "webkvm").Run()

	// Check first: on failure nothing changes.
	check := exec.Command("nft", "-c", "-f", tmp)
	if out, err := check.CombinedOutput(); err != nil {
		return fmt.Errorf("nft check failed: %v: %s", err, strings.TrimSpace(string(out)))
	}
	apply := exec.Command("nft", "-f", tmp)
	if out, err := apply.CombinedOutput(); err != nil {
		return fmt.Errorf("nft apply failed: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// flushTable deletes the whole webkvm table (used when no rules remain).
func (m *Manager) flushTable() error {
	// Delete-if-exists is idempotent and safe.
	cmd := exec.Command("nft", "delete", "table", "ip", "webkvm")
	if err := cmd.Run(); err != nil {
		// "No such file or directory" means the table didn't exist — fine.
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return nil // table absent, nothing to flush
		}
		return err
	}
	return nil
}

func validProto(p string) bool {
	return p == "tcp" || p == "udp" || p == "both"
}

func protoList(p string) []string {
	switch p {
	case "tcp":
		return []string{"tcp"}
	case "udp":
		return []string{"udp"}
	case "both":
		return []string{"tcp", "udp"}
	}
	return nil
}
